### ISSUE TITLE
404

### ISSUE THREAD

**Issue by frontendzzzguy** [furzeface/danielfurze.co.uk#29]
# Project version:
eg: _v1.0.0_

## Issue type:
> Tick one of the below and label if necessary

- [X] Bug
- [ ] Feature suggestion

### Expected behaviour:
> Went to the url https://danielfurze.co.uk/blog/ant-plant-is-awesome expecting to see a page about the awesomeness of Ant Plant

### Actual behaviour:
> returned a 404 error page

### Steps to reproduce the behaviour:
> Go to an internet exploring browser, type in manually https://danielfurze.co.uk/blog/ant-plant-is-awesome taking great care not to get any of the letters mixed up, click, press or prod enter on your device/machine.

**Comment by furzeface** [comment]
LOL [won't fix]
